/* generated by Buddy */
if (window._m_ == null) window._m_ = {};
if (window.require == null) {
  window.require = function require (id) {
    if (!_m_[id]) return;
    return (_m_[id].boot) ? _m_[id]() : _m_[id];
  };
}
_m_['src/index.js']=(function(module,exports){
  module=this;exports=module.exports;

  

  return module.exports;
}).call({exports:{}});