/* generated by Buddy */
if (window._m_ == null) window._m_ = {};
if (window.require == null) {
  window.require = function require (id) {
    if (!_m_[id]) return;
    return (_m_[id].boot) ? _m_[id]() : _m_[id];
  };
}
var global = window.global = window;

(function (global) {
  var babelHelpers = global.babelHelpers = {};

  babelHelpers.classCallCheck = function (instance, Constructor) {
    if (!(instance instanceof Constructor)) {
      throw new TypeError("Cannot call a class as a function");
    }
  };

  babelHelpers.createClass = function () {
    function defineProperties(target, props) {
      for (var i = 0; i < props.length; i++) {
        var descriptor = props[i];
        descriptor.enumerable = descriptor.enumerable || false;
        descriptor.configurable = true;
        if ("value" in descriptor) descriptor.writable = true;
        Object.defineProperty(target, descriptor.key, descriptor);
      }
    }

    return function (Constructor, protoProps, staticProps) {
      if (protoProps) defineProperties(Constructor.prototype, protoProps);
      if (staticProps) defineProperties(Constructor, staticProps);
      return Constructor;
    };
  }();

  babelHelpers.defineProperty = function (obj, key, value) {
    if (key in obj) {
      Object.defineProperty(obj, key, {
        value: value,
        enumerable: true,
        configurable: true,
        writable: true
      });
    } else {
      obj[key] = value;
    }

    return obj;
  };

  babelHelpers.get = function get(object, property, receiver) {
    if (object === null) object = Function.prototype;
    var desc = Object.getOwnPropertyDescriptor(object, property);

    if (desc === undefined) {
      var parent = Object.getPrototypeOf(object);

      if (parent === null) {
        return undefined;
      } else {
        return get(parent, property, receiver);
      }
    } else if ("value" in desc) {
      return desc.value;
    } else {
      var getter = desc.get;

      if (getter === undefined) {
        return undefined;
      }

      return getter.call(receiver);
    }
  };

  babelHelpers.inherits = function (subClass, superClass) {
    if (typeof superClass !== "function" && superClass !== null) {
      throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
    }

    subClass.prototype = Object.create(superClass && superClass.prototype, {
      constructor: {
        value: subClass,
        enumerable: false,
        writable: true,
        configurable: true
      }
    });
    if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;
  };

  babelHelpers.possibleConstructorReturn = function (self, call) {
    if (!self) {
      throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
    }

    return call && (typeof call === "object" || typeof call === "function") ? call : self;
  };

  babelHelpers.taggedTemplateLiteral = function (strings, raw) {
    return Object.freeze(Object.defineProperties(strings, {
      raw: {
        value: Object.freeze(raw)
      }
    }));
  };
})(typeof global === "undefined" ? self : global);
_m_['src/index.js']=(function(module,exports){
  module=this;exports=module.exports;

  'use strict';
  
  var TOUCH_THRESHOLD = 100;
  
  var elSlides = document.querySelector('.slides');
  var isProduction = undefined == 'production';
  var isDevelopment = !isProduction && window.location.hostname == 'localhost';
  var isNotes = window.name == 'notes';
  var startingSlide = isProduction ? 0 : getUrlSlide();
  var model = window.model = parse({
    notes: [],
    noteIndex: 0,
    notesWindow: null,
    slides: [],
    slideIndex: 0,
    steps: [],
    stepIndex: 0
  });
  
  /**
   * Parse slide elements
   * @param {Object} model
   * @returns {Array}
   */
  function parse(model) {
    model.slides = Array.prototype.slice.call(elSlides.children).filter(function (element) {
      return element.tagName == 'HEADER' || element.tagName == 'SECTION';
    });
    model.notes = model.slides.reduce(function (notes, element, idx) {
      notes.push(Array.prototype.slice.call(element.querySelectorAll('.note')));
      return notes;
    }, []);
    model.steps = model.notes.map(function (group) {
      var step = 0;
  
      return group.reduce(function (steps, element, idx) {
        if (element.classList.contains('step')) step++;
        steps.push(step);
        return steps;
      }, []);
    });
  
    return model;
  }
  
  /**
   * Display slide at 'slideIndex'
   * @param {Number} slideIndex
   * @param {Boolean} back
   */
  function changeSlide(slideIndex, back) {
    var current = model.slides[model.slideIndex];
    var next = model.slides[slideIndex];
    var noteIndex = back ? model.notes[slideIndex].length - 1 : 0;
  
    model.stepIndex = back ? model.steps[slideIndex] + 1 : 0;
  
    next.classList.add('show');
    next.classList.remove('hide');
    next.style.zIndex = 100 - slideIndex;
    if (current && next != current) {
      current.classList.add('hide');
      current.addEventListener('transitionend', onTransitionEnd, false);
    }
    changeNote(model.slideIndex, slideIndex, noteIndex);
    model.slideIndex = slideIndex;
    if (isDevelopment) window.history.pushState({}, '', window.location.pathname.replace(/\/\d*$/, '/' + slideIndex));
  }
  
  /**
   * Display note at 'noteIndex'
   * @param {Number} currentSlideIndex
   * @param {Number} nextSlideIndex
   * @param {Number} noteIndex
   */
  function changeNote(currentSlideIndex, nextSlideIndex, noteIndex) {
    var current = model.notes[currentSlideIndex][model.noteIndex];
    var next = model.notes[nextSlideIndex][noteIndex];
  
    if (current) current.style.opacity = 0;
    if (next) next.style.opacity = 1;
    changeStep(nextSlideIndex, model.steps[nextSlideIndex][noteIndex]);
    if (model.notesWindow) model.notesWindow.change(currentSlideIndex, nextSlideIndex, model.noteIndex, noteIndex);
    model.noteIndex = noteIndex;
  }
  
  /**
   * Display step at 'stepIndex'
   * @param {Number} slideIndex
   * @param {Nunber} stepIndex
   */
  function changeStep(slideIndex, stepIndex) {
    var slide = model.slides[slideIndex];
    var classStr = slide.getAttribute('class').replace(/\s?step-\d*\s?/g, '');
  
    for (var i = 1; i <= stepIndex; i++) {
      classStr += ' step-' + i;
    }
    slide.setAttribute('class', classStr);
    model.stepIndex = stepIndex;
  }
  
  /**
   * Display note in remote window
   * @param {Number} currentSlideIndex
   * @param {Number} nextSlideIndex
   * @param {Number} currentNoteIndex
   * @param {Number} nextNoteIndex
   */
  function changeRemoteNote(currentSlideIndex, nextSlideIndex, currentNoteIndex, nextNoteIndex) {
    var currentSlide = model.slides[currentSlideIndex];
    var nextSlide = model.slides[nextSlideIndex];
    var currentNote = model.notes[currentSlideIndex][currentNoteIndex];
    var nextNote = model.notes[nextSlideIndex][nextNoteIndex];
  
    nextSlide.classList.add('show');
    nextSlide.classList.remove('hide');
    nextSlide.style.zIndex = 100 - nextSlideIndex;
    if (currentSlide && nextSlide != currentSlide) {
      currentSlide.classList.add('hide');
      currentSlide.classList.remove('show');
    }
    if (currentNote) currentNote.style.opacity = 0;
    if (nextNote) nextNote.style.opacity = 1;
  }
  
  /**
   * Advance to next step/slide/note
   */
  function next() {
    if (model.noteIndex + 1 < model.notes[model.slideIndex].length) {
      changeNote(model.slideIndex, model.slideIndex, model.noteIndex + 1);
    } else if (model.slideIndex + 1 < model.slides.length) {
      changeSlide(model.slideIndex + 1);
    } else {
      return;
    }
  }
  
  /**
   * Advance to previous step/slide/note
   */
  function prev() {
    if (model.noteIndex - 1 >= 0) {
      changeNote(model.slideIndex, model.slideIndex, model.noteIndex - 1);
    } else if (model.slideIndex - 1 >= 0) {
      changeSlide(model.slideIndex - 1, true);
    } else {
      return;
    }
  }
  
  /**
   * Get current slide index from url
   * @returns {Number}
   */
  function getUrlSlide() {
    var slide = window.location.pathname.split('/').slice(-1)[0];
  
    return parseInt(slide, 0) || 0;
  }
  
  /**
   * Handle key down
   * @param {Event} evt
   */
  function onKeyDown(evt) {
    var key = (evt.key || evt.keyIdentifier).toLowerCase();
  
    if (key === 'arrowright' || key === 'arrowup' || key === 'right' || key === 'up' || key === 'pagedown') {
      next();
    }
    if (key === 'arrowleft' || key === 'arrowdown' || key === 'left' || key === 'down' || key === 'pageup') {
      prev();
    }
  }
  
  /**
   * Handle touch
   * @param {Event} evt
   */
  function onTouchStart(evt) {
    evt.preventDefault();
    var start = evt.layerX;
    var _cb = void 0;
  
    document.documentElement.addEventListener('touchend', _cb = function cb(evt) {
      document.documentElement.removeEventListener('touchend', _cb, false);
      var diff = start - evt.layerX;
  
      if (Math.abs(diff) >= TOUCH_THRESHOLD) diff > 0 ? next() : prev();
    }, false);
  }
  
  /**
   * Handle pop state event
   * @param {Event} evt
   */
  function onPopState(evt) {
    if (evt.state) changeSlide(getUrlSlide());
  }
  
  /**
   * Handle transition end event
   * @param {Event} evt
   */
  function onTransitionEnd(evt) {
    var slide = evt.target;
  
    slide.removeEventListener('transitionend', onTransitionEnd, false);
  
    if (slide.classList.contains('hide') && slide.classList.contains('show')) {
      slide.classList.remove('show');
      slide.style.zIndex = null;
    }
  }
  
  if (!isNotes) {
    document.addEventListener('keyup', onKeyDown, false, { passive: true });
    document.documentElement.addEventListener('touchstart', onTouchStart, false);
  
    hljs.initHighlightingOnLoad();
  
    if (isProduction) {
      model.notesWindow = window.open(window.location.href, 'notes');
      setTimeout(function () {
        changeSlide(startingSlide);
      }, 1000);
    } else {
      if (isDevelopment) {
        document.documentElement.classList.add('dev');
        window.addEventListener('popstate', onPopState, false);
        window.history.replaceState({}, document.title, window.location.pathname);
      }
      changeSlide(startingSlide);
    }
  } else {
    window.change = changeRemoteNote;
    document.documentElement.classList.add('presentation-notes');
  }

  return module.exports;
}).call({exports:{}});